version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      next:
        patterns:
          - "next*"
      react:
        patterns:
          - "react*"
          - "@types/react*"
      radix:
        patterns:
          - "@radix-ui/*"
      ai:
        patterns:
          - "ai"
          - "@ai-sdk/*"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
